services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres-bank-services-db
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-bank-services-db-data
    volumes:
      - postgres:/data/postgres-bank-services-db-data
    ports:
      - 5432:5432
    networks:
      - bank-services-network

  mongodb:
    image: mongo:noble
    container_name: mongodb-bank-services-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bank
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/data/mongodb-bank-services-db-data
    ports:
      - 27017:27017
    networks:
      - bank-services-network

  axon-server:
    image: axoniq/axonserver:latest-jdk-17-nonroot
    container_name: axonserver-bank-services
    environment:
      AXONIQ_AXONSERVER_NAME: axonserver
      AXONIQ_AXONSERVER_DEV_MODE: true
    volumes:
      - axonserver-data:/data/axonserver-bank-services-data
      - axonserver-events:/data/axonserver-bank-services-eventsdata
    ports:
      - 8024:8024
      - 8124:8124

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper-bank-services
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - bank-services-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-bank-services
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - bank-services-network

networks:
  bank-services-network:
    driver: bridge

volumes:
  postgres:
  mongodb:
  axonserver-data:
  axonserver-events: