spring:
  datasource:
    username: bank
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

application:
  config:
    account-url: http://localhost:8084/api/v1/accounts