spring:
  data:
    mongodb:
      username: bank
      password: password
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  mail:
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085