spring:
  datasource:
    username: bank
    password: password
    url: jdbc:postgresql://localhost:5432/transaction
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8086

application:
  config:
    customer-url: http://localhost:8083/api/v1/customers
    account-url: http://localhost:8084/api/v1/accounts